CFLAGS=-fsanitize=integer -fsanitize=undefined -ggdb3 -O0 -std=c11 -Wall -Werror -Wno-unused-parameter -Wextra -Wno-sign-compare -Wshadow -g

all: .

clean:
	rm -f ex1 ex3 ex4 ex7 ex8 ex9 ex10 ex11 ex12 ex13 ex14 ex15 ex16

